import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Toaster } from "@/components/ui/toaster";
=======
>>>>>>> origin/main

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden bg-slate-200`}
      >
        {children}
        <Toaster />
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> origin/main
      </body>
    </html>
  );
}
